namespace MBW.Uponor2MQTT.UhomeUponor.Enums
{
    internal enum UponorThermostats
    {
        EcoProfileActiveCf = 0,
        DehumidifierControlActivation = 1,
        RhControlActivation = 2,
        EcoProfileNumber = 3,
        SetpointWriteEnable = 4,
        CoolingAllowed = 5,
        RhSetpoint = 6,
        MinSetpoint = 7,
        MaxSetpoint = 8,
        MinFloorTemp = 9,
        MaxFloorTemp = 10,
        RoomSetpoint = 11,
        EcoOffset = 12,
        EcoProfileActive = 13,
        HomeAwayModeStatus = 14,
        RoomInDemand = 15,
        RhLimitReached = 16,
        FloorLimitStatus = 17,
        TechnicalAlarm = 18,
        TamperIndication = 19,
        RfAlarm = 20,
        BatteryAlarm = 21,
        RhSensor = 22,
        ThermostatType = 23,
        RegulationMode = 24,
        RoomTemperature = 25,
        RoomTemperatureExt = 26,
        RhValue = 27,
        ChLinkedToTh = 28,
        RoomName = 29,
        UtilizationFactor24H = 30,
        UtilizationFactor7D = 31,
        RegMode = 32,
        ChannelAverage = 33,
        RadiatorHeating = 34,
        Unknown35 = 35,
        Unknown36 = 36,
        Unknown37 = 37,
        Unknown38 = 38,
        Unknown39 = 39
    }
}