# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src

COPY . .
WORKDIR "/src/MBW.Uponor2MQTT/"
RUN dotnet publish -c release -o /app -r linux-musl-x64 --self-contained false

# Final
FROM mcr.microsoft.com/dotnet/runtime:5.0-alpine
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./MBW.Uponor2MQTT"]