# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src

COPY . .
WORKDIR "/src/MBW.Uponor2MQTT/"
RUN dotnet publish -c release -o /app -r linux-arm --self-contained false

# Final
FROM mcr.microsoft.com/dotnet/runtime:5.0-focal
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./MBW.Uponor2MQTT"]