# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY . .
WORKDIR "/src/MBW.Uponor2MQTT/"
RUN dotnet publish -c release -o /app

# Final
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal-amd64
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MBW.Uponor2MQTT.dll"]