# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY . .
WORKDIR "/src/MBW.Uponor2MQTT/"
RUN dotnet publish -c release -o /app

# Final
FROM mcr.microsoft.com/dotnet/runtime:7.0-jammy-arm64v8
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MBW.Uponor2MQTT.dll"]